version: '3.2'
services:
  web:
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    - c:\\temp:/docker-data
    ports:
      - "80:80"
    image: marcoippel/dockerstudy:latest
    networks:
      - frontend
networks:
  frontend:
    name: dockerstudy-basics

