version: '3'
services:
  web:
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    - /cursus:/cursus
    ports:
      - "80:80"
    image: marcoippel/dockerstudy:latest
