version: '3'
services:
  web:
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    ports:
      - "80:80"
    #build: .
    image: marcoippel/dockerstudy:latest

  
